version: "3"
services:
  db:
    image: mariadb
    volumes:
      - "./input:/work:rw"
      - "dbdata:/var/lib/mysql"
    environment:
      - "MARIADB_ROOT_PASSWORD=testing"
    ports:
      - "3306:3306"
    init: true
  mysql2csv:
    depends_on:
      - db
    build: .
    environment:
      DB_USER: "root"
      DB_PASSWORD: "testing"
      DB_HOST: "db"
      LOG_LEVEL: "DEBUG"
      CSV_DIALECT: "excel" # see also: unix ; https://docs.python.org/3/library/csv.html
    command:
      - concept
    volumes:
      - "./output:/work"
volumes:
  dbdata:
